### ISSUE TITLE
Two-camera setup for inference?

### ISSUE THREAD

**Issue by edhyah** [ShunyuanZheng/GPS-Gaussian#11]
Hello,

If I train with an eight-camera setup, and then test using a just two-camera setup, would that be feasible, assuming that the novel viewpoint always lies in between the two cameras? It seems like the inference code only needs two neighboring views?

Thanks!

**Comment by ShunyuanZheng** [comment]
Hi, 

As described in our manuscript, we need to select two cameras from all cameras adjacent to the target novel viewpoint as a working set to conduct novel view interpolation. At each time instant, we only need two specific source views for synthesizing the desired novel view. The selected cameras vary according to the given targeting novel viewpoint.
