### ISSUE TITLE
question about projection_matrix function

### ISSUE THREAD

**Issue by lebron12332** [ShunyuanZheng/GPS-Gaussian#12]
Thank you for your excellent work! What does this function do? What do the ```znear``` and ```zfar``` parameters mean? Do I need to change the parameter values when using the custom data set?
```
projection_matrix = getProjectionMatrix(znear=self.opt.znear, zfar=self.opt.zfar, K=intr, h=height, w=width).transpose(0, 1)
```

**Comment by ShunyuanZheng** [comment]
The ```projection_matrix``` is used to do coordinate transformation which is borrowed from the original 3D-GS code. The ```near``` and ```far``` values will not have a significant impact on performance in GPS-Gaussian. You can also set 0.01 and 100.0 respectively on custom data.
