### ISSUE TITLE
Question about image matting.

### ISSUE THREAD

**Issue by xuxuxuchen** [ShunyuanZheng/GPS-Gaussian#16]
Hello, I saw that your image matting algorithm is very impressive, with high real-time performance and high accuracy. Could you please tell me what algorithm you used?

**Comment by ShunyuanZheng** [comment]
The matting algorithm in the live demo is [RobustVideoMatting](https://github.com/PeterL1n/RobustVideoMatting). And the matting algorithm for the given real-world data is [BackgroundMattingV2](https://github.com/PeterL1n/BackgroundMattingV2), with some failure cases post-processed by [MeiTu](https://cutout.x-design.com/en).

**Comment by xuxuxuchen** [comment]
Thank you very much, it's very useful.
