### ISSUE TITLE
Hi! Great work! but non-Chinese people couldn't access to Baidu

### ISSUE THREAD

**Issue by shi3z** [ShunyuanZheng/GPS-Gaussian#2]
Hi! I have deep impressed your work! It looks amazing.
But we can't access to Baidu netdisk.

Do you have any other option?

Or please descibe detail about data format for training.

Best Regards.

**Comment by ShunyuanZheng** [comment]
Thank you for your interest. I will upload the scripts for rendering training data from human scans. Also, I will seek another netdisk for those who can't access Baidu netdisk.

**Comment by shi3z** [comment]
Hi!
Thank you for uploading to one drive.
I'll try it!

And thank you again for your great work.
I really respect you.

Best regards
