### ISSUE TITLE
Diffenrent size of stage1.pth

### ISSUE THREAD

**Issue by Dragon2938734** [ShunyuanZheng/GPS-Gaussian#20]
excuse me, would you like to solve my confusion that the stage1.pth download from the Onedrive is 74.23M. However, the one that i train by myself base on THU2.0 is 37M. And both them are work. So would you explain the reason of the difference?

Thank you!

**Comment by ShunyuanZheng** [comment]
I have also been confused about it, a possible reason is that I trained the uploaded model with mixed precision.

**Comment by Dragon2938734** [comment]
> I have also been confused about it, a possible reason is that I trained the uploaded model with mixed precision.

Thanks for your reply. I use both the download ckpt and the one trained by my self of stage1 to train stage2 on thu2.0 by "python train_stage2.py", the metric that i got is far higer than the score in Table1 in arxiv preprint. Is there anything that i operate or understand incorrectly?
![image](https://github.com/ShunyuanZheng/GPS-Gaussian/assets/119784366/ad2e3c60-d3f4-4533-8978-b2986c05adbb)

**Comment by ShunyuanZheng** [comment]
In our paper, we evaluate PSNR, SSIM and LPIPS in foreground regions determined by the GT bbox of humans. However, during the training process, we directly evaluate them on whole images for ease of quantization. The background pixels make the PSNR higher than that reported in our paper.

**Comment by Dragon2938734** [comment]
> In our paper, we evaluate PSNR, SSIM and LPIPS in foreground regions determined by the GT bbox of humans. However, during the training process, we directly evaluate them on whole images for ease of quantization. The background pixels make the PSNR higher than that reported in our paper.

Thanks for your reply! Would you plan to release the related evaluate code on PSNR, SSIM and LPIPS? Since i did not find it in the present released code.

**Comment by ShunyuanZheng** [comment]
Our evaluation code is based on [IQA-PyTorch](https://github.com/chaofengc/IQA-PyTorch). I will release the related scripts and update the evaluation guidelines soon. However, since conducting evaluation on either whole images or foreground regions is a common practice, a fair comparison on all compared methods is sufficient for your research.

**Comment by Dragon2938734** [comment]
> Our evaluation code is based on [IQA-PyTorch](https://github.com/chaofengc/IQA-PyTorch). I will release the related scripts and update the evaluation guidelines soon. However, since conducting evaluation on either whole images or foreground regions is a common practice, a fair comparison on all compared methods is sufficient for your research.

Thank you for your patient response!
