### ISSUE TITLE
Training with Multiple GPUs

### ISSUE THREAD

**Issue by Lewis-lv0** [ShunyuanZheng/GPS-Gaussian#23]
Hi @ShunyuanZheng , thanks for sharing the code. Amazing work! Do you plan to release the code of training on multiple gpus because training on a single gpu will take a lot of time. I tried to add the data parallelism but bugs appear. 

I would appreciate it if you could provide some comments or suggestions for faster training.

**Comment by ShunyuanZheng** [comment]
Hi, @Lewis-lv0,  currently I have no plan to release the multi-GPU training code. However, the overall training time on one 3090 GPU takes less than two days, which is acceptable I think : )

**Comment by Lewis-lv0** [comment]
Thanks for your reply. I will close the issue.
