### ISSUE TITLE
scale head

### ISSUE THREAD

**Issue by lebron12332** [ShunyuanZheng/GPS-Gaussian#5]
hello. Excellent work. I noticed that you truncated the scale, as shown in the following code, why do this operation?

# scale head
 scale_out = torch.clamp_max(self.scale_head(out), 0.01)

**Comment by ShunyuanZheng** [comment]
Hi, thanks for your interest.

If not clamp the max value of the scale of Gaussians, it is quite possible to be out of memory at the beginning of the training. Also,  we do not need extremely large Gaussians since the point clouds unprotected from depth maps are dense.

**Comment by lebron12332** [comment]
Thank you. I have another related question. I can understand that using Gaussian expression is more efficient than nerf, but why can it also improve the performance, such as the quality of rendered images? What is your opinion on this?

**Comment by ShunyuanZheng** [comment]
In my opinion, efficient rendering enables us to generate complete views of humans to optimize perceptual metrics like LPIPS in general human-related works, which remains a challenge in NeRF-based methods. But our work benefits more from its differentiable capability, especially to the `position' of points.
