### ISSUE TITLE
Pre-processing in stage1. EOFError: No data left in file. 

### ISSUE THREAD

**Issue by YangBigSir** [ShunyuanZheng/GPS-Gaussian#6]
Hello, this is a great job.  You mentioned: "At the first training time, we do stereo rectify and determine the disparity offline, the processed data will be saved at render_data/rectified_local. This process takes several hours and can extremely speed up the following training scheme. " I didn't skip this pre-processing and set data_root in stage1.yaml to the path of unzipped folder render_data. I have completed 77% of the pre-processing(5245/6816), but the following error occurred at this point: 
`Traceback (most recent call last):
  File "/mnt/GPS-Gaussian/train_stage1.py", line 174, in <module>
    trainer = Trainer(cfg)
  File "/mnt/GPS-Gaussian/train_stage1.py", line 28, in __init__
    self.train_set = StereoHumanDataset(self.cfg.dataset, phase='train')
  File "/mnt/GPS-Gaussian/lib/human_loader.py", line 129, in __init__
    self.save_local_stereo_data()
  File "/mnt/GPS-Gaussian/lib/human_loader.py", line 134, in save_local_stereo_data
    view0_data = self.load_single_view(sample_name, self.opt.source_id[0], hr_img=False,
  File "/mnt/GPS-Gaussian/lib/human_loader.py", line 198, in load_single_view
    intr, extr = np.load(intr_name), np.load(extr_name)
  File "/home/pai/envs/gps_gaussian/lib/python3.10/site-packages/numpy/lib/npyio.py", line 436, in load
    raise EOFError("No data left in file")
EOFError: No data left in file`
What is the reason for this? If you can help me solve this problem, I would greatly appreciate it.
<img width="656" alt="Snipaste_2024-01-01_15-11-30" src="https://github.com/ShunyuanZheng/GPS-Gaussian/assets/100454725/9d9327ea-4472-42d0-9869-3fcbd11914fa">

**Comment by ShunyuanZheng** [comment]
Hi, 
According to the log, I suggest checking the .npy data of sample 5245 to see whether it was damaged during the zip and unzip process. Also, you can render the training data from THuman2.0 scan using the provided scripts instead of downloading the rendered training data.
