### ISSUE TITLE
How can we test with custom dataset!!!

### ISSUE THREAD

**Issue by Winter-Dry** [ShunyuanZheng/GPS-Gaussian#7]
What a nice work! 

I want to test it with the videos captured by multiple cameras, are there any specific data requirements?
I also noticed that the input image size is configured with hard code as 1024x1024, dose it only support the image size with (1024x1024) or (2048x2048)?

**Comment by ShunyuanZheng** [comment]
Hi, 

Thanks for your interest. When testing the custom dataset, we recommend rendering the synthetic data under your targeting scene and camera settings and training the network on these data. The pre-trained model we provide satisfies scenes with 16 cameras and a 2m radius. If you train the GPS-Gaussian on the dataset rendered yourself, there is no limit to the image size. Once I have trained on the image size of 512^2 and 768^2, it works.

**Comment by gjgjgjfff** [comment]
> Hi,
> 
> Thanks for your interest. When testing the custom dataset, we recommend rendering the synthetic data under your targeting scene and camera settings and training the network on these data. The pre-trained model we provide satisfies scenes with 16 cameras and a 2m radius. If you train the GPS-Gaussian on the dataset rendered yourself, there is no limit to the image size. Once I have trained on the image size of 512^2 and 768^2, it works.

Hi,

Is there any command line or python file that converts the own dataset to GPS-Gaussian format?
